### ISSUE TITLE
Compilation fails if mpd isn't installed

### ISSUE THREAD

**Issue by OortCloud42** [Krzysztof-WW/kwstatus#3]
When running `sudo make clean install` on a clean copy of the repo, make returns the following error:
```
modules/mpd.c:28:10: fatal error: mpd/client.h: No such file or directory
   28 | #include <mpd/client.h>
      |          ^~~~~~~~~~~~~~
```
IMO mpd support should be optional as not everyone uses mpd and it's not ✨ the suckless way ✨.

**Comment by Krzysztof-WW** [comment]
Now, mpd module is optional and disabled by default, and any other optional dependencies are in config.mk.
